// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/idzharbae/digital-wallet/src/internal/gateway (interfaces: RabbitMqGateway)
//
// Generated by this command:
//
//	mockgen -destination=gatewaymock/rabbitmqgateway_mock.go -package=gatewaymock github.com/idzharbae/digital-wallet/src/internal/gateway RabbitMqGateway
//

// Package gatewaymock is a generated GoMock package.
package gatewaymock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRabbitMqGateway is a mock of RabbitMqGateway interface.
type MockRabbitMqGateway struct {
	ctrl     *gomock.Controller
	recorder *MockRabbitMqGatewayMockRecorder
}

// MockRabbitMqGatewayMockRecorder is the mock recorder for MockRabbitMqGateway.
type MockRabbitMqGatewayMockRecorder struct {
	mock *MockRabbitMqGateway
}

// NewMockRabbitMqGateway creates a new mock instance.
func NewMockRabbitMqGateway(ctrl *gomock.Controller) *MockRabbitMqGateway {
	mock := &MockRabbitMqGateway{ctrl: ctrl}
	mock.recorder = &MockRabbitMqGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRabbitMqGateway) EXPECT() *MockRabbitMqGatewayMockRecorder {
	return m.recorder
}

// PublishMessage mocks base method.
func (m *MockRabbitMqGateway) PublishMessage(arg0, arg1 string, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishMessage", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishMessage indicates an expected call of PublishMessage.
func (mr *MockRabbitMqGatewayMockRecorder) PublishMessage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMessage", reflect.TypeOf((*MockRabbitMqGateway)(nil).PublishMessage), arg0, arg1, arg2)
}
